#!/bin/bash

major=`psql -V 2> /dev/null | cut -d' ' -f3 | cut -d'.' -f1`
minor=`psql -V 2> /dev/null | cut -d' ' -f3 | cut -d'.' -f2`
patch=`psql -V 2> /dev/null | cut -d' ' -f3 | cut -d'.' -f3`

if [[ $major == 10 ]] ; then
  echo $major
else
  echo $major.$minor
fi
